#ifndef NET_MINECRAFT_WORLD_AETHER__AetherDimension_H__
#define NET_MINECRAFT_WORLD_AETHER__AetherDimension_H__

//
// The Aether dimension: bright sky, day/night cycle, no ceiling, floating
// islands generated by AetherRandomLevelSource.
//

#include "../level/dimension/Dimension.h"

class AetherDimension : public Dimension {
	typedef Dimension super;
public:
	AetherDimension();
	virtual ~AetherDimension();

	virtual void init();
	virtual ChunkSource* createRandomLevelSource();
	virtual void updateLightRamp();
	virtual bool isValidSpawn(int x, int z);
	virtual float getTimeOfDay(long time, float a);
	virtual Vec3 getFogColor(float td, float a);
	virtual bool mayRespawn();
	virtual bool isNaturalDimension();
};

#endif /*NET_MINECRAFT_WORLD_AETHER__AetherDimension_H__*/
