#ifndef NET_MINECRAFT_WORLD_ENTITY__EntityRendererId_H__
#define NET_MINECRAFT_WORLD_ENTITY__EntityRendererId_H__

enum EntityRendererId {
    ER_DEFAULT_RENDERER,
	ER_QUERY_RENDERER,
    ER_TNT_RENDERER,
    ER_HUMANOID_RENDERER,
	ER_ITEM_RENDERER,
	ER_TRIPODCAMERA_RENDERER,
	ER_CHICKEN_RENDERER,
	ER_COW_RENDERER,
	ER_PIG_RENDERER,
	ER_SHEEP_RENDERER,
	ER_SHEEP_FUR_RENDERER,
	ER_ZOMBIE_RENDERER,
	ER_SKELETON_RENDERER,
	ER_SPIDER_RENDERER,
	ER_CREEPER_RENDERER,
	ER_ARROW_RENDERER,
	ER_PLAYER_RENDERER,
	ER_THROWNEGG_RENDERER,
	ER_SNOWBALL_RENDERER,
	ER_PAINTING_RENDERER,
    ER_FALLINGTILE_RENDERER
};

#endif /*NET_MINECRAFT_WORLD_ENTITY__EntityRendererId_H__*/
