#!/usr/bin/env python3
"""
Generates the item sprites for the RPG mythic gear and writes them into
data/images/gui/items.png (16x16 cells, 16 columns).

Run from the repository root:  python3 tools/gear_sprites.py
Requires only the Python standard library.
"""
import os, sys, struct, zlib

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
ITEMS_PNG = os.path.join(ROOT, 'data', 'images', 'gui', 'items.png')

# ----------------------------------------------------------------------
# Minimal PNG IO
# ----------------------------------------------------------------------
def read_png(path):
    d = open(path, 'rb').read(); pos = 8; idat = b''
    while pos < len(d):
        n, = struct.unpack('>I', d[pos:pos + 4]); t = d[pos + 4:pos + 8]; c = d[pos + 8:pos + 8 + n]
        if t == b'IHDR': w, h, bd, ct = struct.unpack('>IIBB', c[:10])
        if t == b'IDAT': idat += c
        pos += 12 + n
    assert bd == 8 and ct == 6, 'expected 8-bit RGBA png'
    raw = zlib.decompress(idat); stride = w * 4
    rows = []; prev = bytearray(stride); i = 0
    for y in range(h):
        f = raw[i]; i += 1; line = bytearray(raw[i:i + stride]); i += stride
        for x in range(stride):
            a = line[x - 4] if x >= 4 else 0; b = prev[x]; c = prev[x - 4] if x >= 4 else 0
            if f == 1: line[x] = (line[x] + a) & 255
            elif f == 2: line[x] = (line[x] + b) & 255
            elif f == 3: line[x] = (line[x] + (a + b) // 2) & 255
            elif f == 4:
                p = a + b - c; pa = abs(p - a); pb = abs(p - b); pc = abs(p - c)
                line[x] = (line[x] + (a if pa <= pb and pa <= pc else b if pb <= pc else c)) & 255
        rows.append(line); prev = line
    return w, h, rows

def write_png(path, w, h, rows):
    raw = b''.join(b'\x00' + bytes(r) for r in rows)
    def chunk(t, c): return struct.pack('>I', len(c)) + t + c + struct.pack('>I', zlib.crc32(t + c) & 0xffffffff)
    open(path, 'wb').write(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0))
                           + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))

# ----------------------------------------------------------------------
# Palettes. Each armor set / weapon uses letters mapped to RGB.
#   . = transparent   k = outline
# ----------------------------------------------------------------------
def pal(**kw):
    p = {'.': None, 'k': (20, 18, 24)}
    p.update(kw)
    return p

SETS = {
    # name: (dark, mid, light, accent)
    'dragonscale': pal(d=(120, 22, 18), m=(190, 48, 30), l=(240, 110, 50), a=(255, 210, 80)),
    'shadowweave': pal(d=(28, 22, 44), m=(58, 48, 90), l=(96, 84, 140), a=(150, 90, 220)),
    'titanforged': pal(d=(70, 78, 92), m=(120, 130, 150), l=(190, 200, 215), a=(235, 180, 60)),
    'lifebloom':   pal(d=(30, 90, 40), m=(60, 150, 70), l=(130, 210, 110), a=(250, 120, 170)),
    'stormcaller': pal(d=(20, 50, 100), m=(40, 100, 180), l=(110, 180, 240), a=(255, 245, 120)),
}

# Armor templates (16x16). Letters: k outline, d dark, m mid, l light, a accent.
HELMET = """
................
................
.....kkkkkk.....
....kllllllk....
...klmmmmmmlk...
...kmmammammk...
...kmmmmmmmmk...
...kdmmmmmmdk...
...kdkkkkkkdk...
...kdk....kdk...
...kkk....kkk...
................
................
................
................
................
"""
CHESTPLATE = """
................
................
..kkkk....kkkk..
.klllkkkkkkllk..
.kmmmlmmmmlmmmk.
.kmmklmmmmlkmmk.
.kdkkmmammmkkdk.
..k.kmmmmmmk.k..
....kmmammmk....
....kmmmmmmk....
....kdmmmmdk....
....kddmmddk....
....kkkkkkkk....
................
................
................
"""
LEGGINGS = """
................
................
....kkkkkkkk....
...kllllllllk...
...kmmmmmmmmk...
...kmmakkammk...
...kmmk..kmmk...
...kmmk..kmmk...
...kmmk..kmmk...
...kdmk..kmdk...
...kdmk..kmdk...
...kddk..kddk...
...kkkk..kkkk...
................
................
................
"""
BOOTS = """
................
................
................
................
...kkkk..kkkk...
...kllk..kllk...
...kmmk..kmmk...
...kmak..kamk...
...kmmk..kmmk...
..kkmmk..kmmkk..
.kdmmmk..kmmmdk.
.kddddk..kddddk.
.kkkkkk..kkkkkk.
................
................
................
"""

# Weapons. Each has its own palette.
WEAPONS = {
 'greatsword_obsidian': (pal(b=(60, 30, 90), s=(110, 70, 160), e=(180, 140, 230), h=(120, 80, 40), g=(220, 180, 70)), """
............kkk.
...........kbsk.
..........kbsek.
.........kbsek..
........kbsek...
.......kbsek....
..kk..kbsek.....
..kgkkbsek......
...kgksek.......
....kgkk........
...kgkgk........
..khk.kgk.......
.khk...kk.......
khk.............
kk..............
................
"""),
 'katana_blazing': (pal(b=(250, 200, 60), s=(255, 120, 30), e=(255, 245, 200), h=(60, 20, 20), g=(200, 40, 20)), """
..............k.
.............kek
............kesk
...........kesk.
..........kesk..
.........kesk...
........kesk....
.......kesk.....
......kesk......
.....kesk.......
....kgsk........
...kgkk.........
..khk...........
.khk............
khk.............
kk..............
"""),
 'sword_frostbrand': (pal(b=(160, 220, 255), s=(90, 170, 240), e=(240, 250, 255), h=(40, 60, 110), g=(200, 230, 255)), """
.............kk.
............kbek
...........kbsek
..........kbsek.
.........kbsek..
........kbsek...
.......kbsek....
...k..kbsek.....
..kgkkbsek......
...kgksek.......
....kgkk........
...kgkgk........
..khk.kgk.......
.khk...kk.......
khk.............
kk..............
"""),
 'dagger_vampire': (pal(b=(170, 20, 40), s=(220, 40, 60), e=(255, 130, 140), h=(30, 10, 15), g=(120, 100, 110)), """
................
................
................
..........kk....
.........kbek...
........kbsek...
.......kbsek....
......kbsek.....
.....kbsek......
...kkksek.......
..kggkkk........
...kgkgk........
..khk.kk........
.khk............
khk.............
kk..............
"""),
 'hammer_thunder': (pal(b=(90, 100, 120), s=(150, 160, 180), e=(220, 225, 235), h=(110, 70, 30), g=(255, 240, 100)), """
.......kkkkkkk..
......kbbbbbbbk.
.....kbssssssbk.
.....kbseeeesbk.
.....kbsegsesbk.
.....kbssgsssbk.
......kbbgbbbk..
.......kkgkk....
.......khk......
......khk.......
.....khk........
....khk.........
...khk..........
..khk...........
.khk............
.kk.............
"""),
 'fang_venom': (pal(b=(60, 120, 30), s=(110, 200, 50), e=(200, 255, 120), h=(40, 30, 20), g=(140, 100, 60)), """
................
..............k.
.............kek
............kesk
...........kesk.
..........kesk..
.........kesk...
........kesk....
.......kesk.....
......kesk......
.....kbsk.......
....kgkk........
...khk..........
..khk...........
.khk............
kk..............
"""),
 'axe_executioner': (pal(b=(50, 50, 60), s=(110, 110, 125), e=(190, 190, 205), h=(80, 45, 25), g=(190, 30, 30)), """
.......kkkkk....
.....kkbbbbbk...
....kbssssssk...
...kbsseeessk...
...kbsseeessk...
...kbsssgsssk...
....kbsssssk....
.....kkkhkk.....
.......khk......
......khk.......
.....khk........
....khk.........
...khk..........
..khk...........
.khk............
.kk.............
"""),
 'scythe_soulreaper': (pal(b=(40, 40, 60), s=(120, 130, 170), e=(210, 220, 250), h=(50, 30, 60), g=(120, 240, 200)), """
.....kkkkkkk....
...kkbssssssk...
..kbsskkkksek...
.kbsk....kkek...
.kbk......kek...
.kk.......kek...
..........kk....
.........khk....
........khk.....
.......khk......
......khk.......
.....khk........
....kgk.........
...khk..........
..khk...........
..kk............
"""),
 'blade_wind': (pal(b=(200, 240, 230), s=(120, 220, 200), e=(255, 255, 255), h=(60, 90, 90), g=(180, 240, 220)), """
..............k.
.............kek
............kesk
...........kesk.
..........kesk..
.........kesk...
........kesk....
.......kesk.....
..k...kesk......
.kgk.kesk.......
..kgkbsk........
...kgkk.........
..khkgk.........
.khk.kk.........
khk.............
kk..............
"""),
 'longbow_ranger': (pal(b=(90, 60, 30), s=(150, 100, 50), e=(210, 160, 90), h=(230, 230, 230), g=(120, 240, 120)), """
..........kkk...
........kkbsk...
.......kbsek....
......kbsek.h...
.....kbsek..h...
.....kbsk...h...
....kbsk....h...
....kgk.....h...
....kgk.....h...
....kbsk....h...
.....kbsk...h...
.....kbsek..h...
......kbsek.h...
.......kbsek....
........kkbsk...
..........kkk...
"""),
}

def render(template, palette):
    lines = [l for l in template.strip('\n').split('\n')]
    assert len(lines) == 16, len(lines)
    out = []
    for l in lines:
        assert len(l) == 16, repr(l)
        row = []
        for ch in l:
            c = palette.get(ch)
            row.append((0, 0, 0, 0) if c is None else (c[0], c[1], c[2], 255))
        out.append(row)
    return out

def blit(rows, col, rowi, sprite):
    for y in range(16):
        for x in range(16):
            r, g, b, a = sprite[y][x]
            o = ((col) + (rowi * 16 + y) * 16 * 16) * 0  # unused
            idx = (col * 16 + x) * 4
            line = rows[rowi * 16 + y]
            line[idx:idx + 4] = bytes((r, g, b, a))

# Icon layout — must match RPG_ARMOR_ICON / RPG_WEAPON_ICON in src/world/item/Item.cpp
ARMOR_CELLS = {
    'dragonscale': [(0, 14), (1, 14), (2, 14), (3, 14)],
    'shadowweave': [(4, 14), (5, 14), (6, 14), (7, 14)],
    'titanforged': [(8, 14), (9, 14), (10, 14), (11, 14)],
    'lifebloom':   [(12, 14), (13, 14), (14, 14), (15, 14)],
    'stormcaller': [(0, 12), (1, 12), (2, 12), (3, 12)],
}
WEAPON_CELLS = {
    'greatsword_obsidian': (4, 12), 'katana_blazing': (5, 12), 'sword_frostbrand': (6, 12), 'dagger_vampire': (7, 12),
    'hammer_thunder': (8, 12), 'fang_venom': (9, 12), 'axe_executioner': (10, 12), 'scythe_soulreaper': (11, 12),
    'blade_wind': (0, 11), 'longbow_ranger': (1, 11),
}

def main():
    w, h, rows = read_png(ITEMS_PNG)
    assert (w, h) == (256, 256)
    for name, cells in ARMOR_CELLS.items():
        p = SETS[name]
        for (c, r), tpl in zip(cells, [HELMET, CHESTPLATE, LEGGINGS, BOOTS]):
            blit(rows, c, r, render(tpl, p))
    for name, (c, r) in WEAPON_CELLS.items():
        p, tpl = WEAPONS[name]
        blit(rows, c, r, render(tpl, p))
    write_png(ITEMS_PNG, w, h, rows)
    print('updated', ITEMS_PNG)

if __name__ == '__main__':
    main()


# ----------------------------------------------------------------------
# Worn armor textures: recolour data/images/armor/diamond_{1,2}.png per set
# ----------------------------------------------------------------------
def recolour_armor():
    armor_dir = os.path.join(ROOT, 'data', 'images', 'armor')
    for name, p in SETS.items():
        d, m, l, a = p['d'], p['m'], p['l'], p['a']
        for layer in (1, 2):
            w, h, rows = read_png(os.path.join(armor_dir, 'diamond_%d.png' % layer))
            out = []
            for y in range(h):
                line = bytearray(rows[y])
                for x in range(w):
                    r, g, b, al = line[x * 4:x * 4 + 4]
                    if al == 0: continue
                    lum = (r * 299 + g * 587 + b * 114) / 1000.0 / 255.0
                    # map luminance onto the set's dark -> mid -> light ramp
                    if lum < 0.45:
                        t = lum / 0.45; c0, c1 = d, m
                    else:
                        t = (lum - 0.45) / 0.55; c0, c1 = m, l
                    col = tuple(int(c0[i] + (c1[i] - c0[i]) * t) for i in range(3))
                    line[x * 4:x * 4 + 3] = bytes(col)
                out.append(line)
            write_png(os.path.join(armor_dir, '%s_%d.png' % (name, layer)), w, h, out)
            print('wrote', name, layer)

if __name__ == '__main__':
    recolour_armor()
